// Blocks
import 'CommonBlocks/header/header';
import 'CommonBlocks/input-box/__input/__input';
import 'CommonBlocks/dropdown/dropdown';
import 'CommonBlocks/form/form';
import 'CommonBlocks/room-card/room-card';
import 'CommonBlocks/range/range';
// Pages
import 'Pages/form-elements/form-elements';
import 'Pages/search-room-filter/search-room-filter';
import 'Pages/room-details/room-details';
import 'Pages/cards/cards';
import 'Pages/register/register';
